In [1]:
def func2(n):
    
    # list to store students detail
    student_details = []
    
    # iterate through the loop n times
    # to store the details for n student.
    for i in range(n):
        print('Enter details for student Number:',i+1)
        try:
            sname = input('Please enter student Name: ')
            sgrade = int(input('Please enter student Grade: '))
            print()
            if sname == '': # if name is empty
                print('Please enter a valid name')
                
            # store name and grade as a tuple of the form (name,grade)
            student_details.append((sname,sgrade))
        except:
            print('Wrong inputs.')
            
    print('Name of student with Maximum Exam Grade\n')
    print("{:<20} {:<5}".format('Name','Grade'))
    print(30*"-") # print '-' , 30 times for better print formatting
    
    # get the maximum grade
    max_grade = max(student_details,key=lambda x:x[1])
    
    # print name of all the students having grade equal to maximum grade
    for name,grade in student_details:
        if grade == max_grade[1]:
            print("{:<20} {:<5}".format(name,grade))

In [2]:
func2(5)

Please enter student Name: Bob
Please enter student Grade: 89

Enter details for student Number: 2
Please enter student Name: Jack
Please enter student Grade: 74

Enter details for student Number: 3
Please enter student Name: ABC
Please enter student Grade: 73

Enter details for student Number: 4
Please enter student Name: Bob
Please enter student Grade: 81

Enter details for student Number: 5
Please enter student Name: Michael
Please enter student Grade: 89

Name of student with Maximum Exam Grade

Name                 Grade
------------------------------
Bob                  89
Michael              89

In [ ]:
#ICE BofA US Corporate Index Option-Adjusted Spread BAMLC0A0CM
#ICE BofA US High Yield Index Option-Adjusted Spread (BAMLH0A0HYM2)
 #Industrial Production: Total Index (INDPRO)

In [147]:
import pandas as pd

In [148]:
df1 = pd.read_csv('BAMLC0A0CM.csv')

In [149]:
df2 = pd.read_csv('BAMLH0A0HYM2.csv')

In [150]:
df3 = pd.read_csv('INDPRO.csv')

In [151]:
df1.head()

         DATE BAMLC0A0CM
0  20-12-2007       2.04
1  21-12-2007       2.03
2  24-12-2007       2.03
3  25-12-2007          .
4  26-12-2007       2.03

In [152]:
df2.head()

         DATE BAMLH0A0HYM2
0  20-12-2007         5.79
1  21-12-2007         5.68
2  24-12-2007         5.65
3  25-12-2007            .
4  26-12-2007         5.59

In [153]:
df3.head()

         DATE    INDPRO
0  01-12-2007  102.4621
1  01-01-2008  102.3148
2  01-02-2008  101.9384
3  01-03-2008  101.5904
4  01-04-2008  100.9098

In [154]:
df1.dtypes

DATE          object
BAMLC0A0CM    object
dtype: object

In [155]:
df = pd.concat([df1,df2,df3],axis=1)

In [156]:
df_concat = pd.merge(df1, df2 ,on='DATE', how='outer')

In [157]:
df = pd.merge(df_concat, df3 ,on='DATE', how='outer')

In [158]:
pd.set_option('display.max_rows', 7316)

In [159]:
df

            DATE BAMLC0A0CM BAMLH0A0HYM2    INDPRO
0     20-12-2007       2.04         5.79       NaN
1     21-12-2007       2.03         5.68       NaN
2     24-12-2007       2.03         5.65       NaN
3     25-12-2007          .            .       NaN
4     26-12-2007       2.03         5.59       NaN
5     27-12-2007       2.03         5.64       NaN
6     28-12-2007       2.03         5.73       NaN
7     31-12-2007       2.03         5.92       NaN
8     01-01-2008          .            .  102.3148
9     02-01-2008       2.05          6.1       NaN
10    03-01-2008       2.06         6.17       NaN
11    04-01-2008       2.09         6.36       NaN
12    07-01-2008       2.11         6.45       NaN
13    08-01-2008       2.12         6.51       NaN
14    09-01-2008       2.17         6.73       NaN
15    10-01-2008       2.17         6.63       NaN
16    11-01-2008       2.17         6.68       NaN
17    14-01-2008       2.16         6.66       NaN
18    15-01-2008       2.18         6.74       NaN
19    16-01-2008       2.19         6.83       NaN
20    17-01-2008       2.22         6.99       NaN
21    18-01-2008       2.24         7.04       NaN
22    21-01-2008       2.24         7.05       NaN
23    22-01-2008       2.31         7.39       NaN
24    23-01-2008       2.33         7.48       NaN
25    24-01-2008        2.3         7.12       NaN
26    25-01-2008        2.3         6.99       NaN
27    28-01-2008       2.29         7.03       NaN
28    29-01-2008       2.28         6.85       NaN
29    30-01-2008       2.29         6.78       NaN
30    31-01-2008        2.3         6.95       NaN
31    01-02-2008        2.3         6.96  101.9384
32    04-02-2008       2.31         6.92       NaN
33    05-02-2008       2.31         7.06       NaN
34    06-02-2008       2.31         7.09       NaN
35    07-02-2008       2.33          7.1       NaN
36    08-02-2008       2.34         7.25       NaN
37    11-02-2008       2.36         7.37       NaN
38    12-02-2008       2.37         7.37       NaN
39    13-02-2008       2.38         7.38       NaN
40    14-02-2008       2.38         7.25       NaN
41    15-02-2008       2.39          7.3       NaN
42    18-02-2008       2.39          7.3       NaN
43    19-02-2008       2.39         7.25       NaN
44    20-02-2008        2.4         7.25       NaN
45    21-02-2008       2.41         7.35       NaN
46    22-02-2008       2.42         7.35       NaN
47    25-02-2008       2.42         7.21       NaN
48    26-02-2008       2.43         7.17       NaN
49    27-02-2008       2.44         7.18       NaN
50    28-02-2008       2.47         7.37       NaN
51    29-02-2008       2.52         7.67       NaN
52    03-03-2008       2.55         7.75       NaN
53    04-03-2008        2.6         7.76       NaN
54    05-03-2008       2.64         7.68       NaN
55    06-03-2008       2.72         7.79       NaN
56    07-03-2008       2.75         7.92       NaN
57    10-03-2008        2.8         8.08       NaN
58    11-03-2008       2.84         7.95       NaN
59    12-03-2008       2.86         8.13       NaN
60    13-03-2008       2.92         8.27       NaN
61    14-03-2008       2.97         8.38       NaN
62    17-03-2008       3.03         8.62       NaN
63    18-03-2008       3.02         8.39       NaN
64    19-03-2008       3.03         8.37       NaN
65    20-03-2008       3.05          8.4       NaN
66    21-03-2008          .            .       NaN
67    24-03-2008       3.01         8.07       NaN
68    25-03-2008       2.99         7.97       NaN
69    26-03-2008       2.98         7.99       NaN
70    27-03-2008       2.99         7.94       NaN
71    28-03-2008       2.99         7.99       NaN
72    31-03-2008          3         8.21       NaN
73    01-04-2008       2.98         8.02  100.9098
74    02-04-2008       2.94         7.86       NaN
75    03-04-2008       2.92         7.78       NaN
76    04-04-2008       2.89         7.76       NaN
77    07-04-2008       2.85         7.54       NaN
78    08-04-2008       2.84         7.58       NaN
79    09-04-2008       2.86         7.71       NaN
80    10-04-2008       2.86          7.7       NaN
81    11-04-2008       2.87         7.76       NaN
82    14-04-2008       2.87         7.74       NaN
83    15-04-2008       2.85         7.65       NaN
84    16-04-2008       2.84         7.46       NaN
85    17-04-2008       2.82         7.36       NaN
86    18-04-2008       2.77         7.15       NaN
87    21-04-2008       2.74         7.13       NaN
88    22-04-2008       2.72         7.07       NaN
89    23-04-2008        2.7         7.05       NaN
90    24-04-2008       2.68         6.92       NaN
91    25-04-2008       2.67         6.84       NaN
92    28-04-2008       2.65         6.85       NaN
93    29-04-2008       2.63         6.86       NaN
94    30-04-2008        2.6         6.86       NaN
95    01-05-2008       2.57         6.81  100.3073
96    02-05-2008       2.53         6.64       NaN
97    05-05-2008       2.52         6.65       NaN
98    06-05-2008       2.52          6.7       NaN
99    07-05-2008       2.52         6.72       NaN
100   08-05-2008       2.53         6.83       NaN
101   09-05-2008       2.53          6.9       NaN
102   12-05-2008       2.53          6.9       NaN
103   13-05-2008       2.51         6.76       NaN
104   14-05-2008        2.5         6.65       NaN
105   15-05-2008        2.5         6.69       NaN
106   16-05-2008       2.49         6.63       NaN
107   19-05-2008       2.49          6.6       NaN
108   20-05-2008        2.5         6.68       NaN
109   21-05-2008        2.5         6.64       NaN
110   22-05-2008       2.51         6.59       NaN
111   23-05-2008       2.52          6.7       NaN
112   26-05-2008       2.52          6.7       NaN
113   27-05-2008       2.53         6.72       NaN
114   28-05-2008       2.52         6.61       NaN
115   29-05-2008        2.5         6.55       NaN
116   30-05-2008        2.5         6.57       NaN
117   31-05-2008       2.48         6.53       NaN
118   02-06-2008       2.49         6.67       NaN
119   03-06-2008        2.5         6.78       NaN
120   04-06-2008       2.51         6.79       NaN
121   05-06-2008        2.5         6.63       NaN
122   06-06-2008        2.5         6.68       NaN
123   09-06-2008       2.48         6.58       NaN
124   10-06-2008       2.49         6.49       NaN
125   11-06-2008        2.5         6.56       NaN
126   12-06-2008       2.49         6.43       NaN
127   13-06-2008       2.49         6.39       NaN
128   16-06-2008       2.49         6.37       NaN
129   17-06-2008       2.48          6.4       NaN
130   18-06-2008        2.5         6.53       NaN
131   19-06-2008        2.5         6.53       NaN
132   20-06-2008       2.54          6.7       NaN
133   23-06-2008       2.55         6.76       NaN
134   24-06-2008       2.58         7.01       NaN
135   25-06-2008       2.59         7.02       NaN
136   26-06-2008       2.66         7.27       NaN
137   27-06-2008       2.68         7.41       NaN
138   30-06-2008       2.74         7.35       NaN
139   01-07-2008       2.77         7.48   99.6124
140   02-07-2008       2.77         7.53       NaN
141   03-07-2008       2.79         7.63       NaN
142   04-07-2008       2.79         7.63       NaN
143   07-07-2008       2.79         7.76       NaN
144   08-07-2008       2.82         7.87       NaN
145   09-07-2008       2.84         7.82       NaN
146   10-07-2008       2.85          7.9       NaN
147   11-07-2008       2.88         7.88       NaN
148   14-07-2008       2.88         7.89       NaN
149   15-07-2008       2.94         8.06       NaN
150   16-07-2008       2.98         8.01       NaN
151   17-07-2008       2.97         7.79       NaN
152   18-07-2008       2.97         7.67       NaN
153   21-07-2008       2.96         7.58       NaN
154   22-07-2008       2.97          7.6       NaN
155   23-07-2008       2.94         7.46       NaN
156   24-07-2008       2.96         7.64       NaN
157   25-07-2008       2.96          7.6       NaN
158   28-07-2008       2.98         7.79       NaN
159   29-07-2008       2.98         7.82       NaN
160   30-07-2008       2.98         7.81       NaN
161   31-07-2008          3            8       NaN
162   01-08-2008          3         8.13   98.0601
163   04-08-2008          3         8.14       NaN
164   05-08-2008          3         8.11       NaN
165   06-08-2008          3         8.05       NaN
166   07-08-2008       3.01         8.16       NaN
167   08-08-2008       3.01         8.14       NaN
168   11-08-2008       3.01         8.07       NaN
169   12-08-2008       3.03         8.11       NaN
170   13-08-2008       3.03         8.09       NaN
171   14-08-2008       3.04         8.11       NaN
172   15-08-2008       3.05         8.12       NaN
173   18-08-2008       3.06         8.17       NaN
174   19-08-2008       3.08         8.23       NaN
175   20-08-2008       3.11          8.3       NaN
176   21-08-2008       3.12         8.29       NaN
177   22-08-2008       3.12         8.25       NaN
178   25-08-2008       3.14         8.32       NaN
179   26-08-2008       3.15         8.32       NaN
180   27-08-2008       3.15         8.34       NaN
181   28-08-2008       3.16         8.29       NaN
182   29-08-2008       3.16         8.28       NaN
183   31-08-2008       3.17         8.36       NaN
184   01-09-2008       3.17         8.36   93.8451
185   02-09-2008       3.19         8.42       NaN
186   03-09-2008        3.2         8.48       NaN
187   04-09-2008       3.21         8.55       NaN
188   05-09-2008       3.22         8.55       NaN
189   08-09-2008       3.21         8.46       NaN
190   09-09-2008       3.24         8.53       NaN
191   10-09-2008       3.28         8.55       NaN
192   11-09-2008       3.39         8.62       NaN
193   12-09-2008       3.44         8.54       NaN
194   15-09-2008        3.8         9.05       NaN
195   16-09-2008       4.11         9.29       NaN
196   17-09-2008       4.28         9.64       NaN
197   18-09-2008        4.4         9.83       NaN
198   19-09-2008       4.15         9.21       NaN
199   22-09-2008       4.09         9.21       NaN
200   23-09-2008       4.17         9.39       NaN
201   24-09-2008       4.26         9.67       NaN
202   25-09-2008       4.36         9.87       NaN
203   26-09-2008       4.59        10.25       NaN
204   29-09-2008       4.65        10.75       NaN
205   30-09-2008       4.55        10.96       NaN
206   01-10-2008       4.61        11.24   94.7036
207   02-10-2008       4.87           12       NaN
208   03-10-2008       4.91        12.24       NaN
209   06-10-2008       5.08        13.07       NaN
210   07-10-2008       5.14        13.18       NaN
211   08-10-2008       5.26        13.51       NaN
212   09-10-2008       5.35        13.91       NaN
213   10-10-2008       5.81        15.36       NaN
214   13-10-2008       5.82        15.38       NaN
215   14-10-2008       5.49         14.5       NaN
216   15-10-2008       5.54        15.14       NaN
217   16-10-2008       5.73        15.72       NaN
218   17-10-2008       5.87        15.95       NaN
219   20-10-2008       5.91        15.76       NaN
220   21-10-2008       5.94        15.87       NaN
221   22-10-2008       5.96        16.05       NaN
222   23-10-2008       5.98        16.34       NaN
223   24-10-2008       6.09        16.69       NaN
224   27-10-2008       6.14        16.81       NaN
225   28-10-2008       6.15        16.67       NaN
226   29-10-2008       6.18        16.21       NaN
227   30-10-2008       6.17        15.91       NaN
228   31-10-2008       6.06        16.17       NaN
229   03-11-2008       6.06        16.29       NaN
230   04-11-2008       6.03        16.18       NaN
231   05-11-2008       5.95        16.08       NaN
232   06-11-2008       5.94        16.19       NaN
233   07-11-2008       5.91        16.31       NaN
234   10-11-2008       5.86        16.35       NaN
235   11-11-2008       5.86        16.36       NaN
236   12-11-2008       5.87        16.84       NaN
237   13-11-2008        5.9        17.06       NaN
238   14-11-2008       5.88        17.16       NaN
239   17-11-2008       5.93        17.43       NaN
240   18-11-2008       5.98        17.96       NaN
241   19-11-2008       6.06        18.61       NaN
242   20-11-2008       6.22        19.48       NaN
243   21-11-2008       6.36        19.92       NaN
244   24-11-2008       6.36        19.87       NaN
245   25-11-2008       6.38        19.86       NaN
246   26-11-2008       6.39        19.76       NaN
247   27-11-2008       6.39        19.77       NaN
248   28-11-2008       6.42        19.78       NaN
249   30-11-2008       6.41        19.88       NaN
250   01-12-2008       6.44         20.2   90.8250
251   02-12-2008        6.5        20.19       NaN
252   03-12-2008       6.53        20.39       NaN
253   04-12-2008       6.55        20.54       NaN
254   05-12-2008       6.56        20.74       NaN
255   08-12-2008       6.55        20.62       NaN
256   09-12-2008       6.55        20.59       NaN
257   10-12-2008       6.54        20.66       NaN
258   11-12-2008       6.52        20.92       NaN
259   12-12-2008       6.52         21.3       NaN
260   15-12-2008       6.51        21.82       NaN
261   16-12-2008       6.51        21.44       NaN
262   17-12-2008       6.42        21.06       NaN
263   18-12-2008       6.35        20.72       NaN
264   19-12-2008        6.3        20.43       NaN
265   22-12-2008       6.28        20.18       NaN
266   23-12-2008       6.25        19.82       NaN
267   24-12-2008       6.21        19.79       NaN
268   25-12-2008          .            .       NaN
269   26-12-2008        6.2        19.55       NaN
270   29-12-2008       6.19        19.25       NaN
271   30-12-2008       6.12        18.48       NaN
272   31-12-2008       6.04        18.12       NaN
273   01-01-2009          .            .   88.5830
274   02-01-2009       6.03        17.84       NaN
275   05-01-2009       5.96        17.44       NaN
276   06-01-2009       5.82        16.68       NaN
277   07-01-2009       5.74        16.42       NaN
278   08-01-2009       5.67        16.67       NaN
279   09-01-2009       5.62        16.65       NaN
280   12-01-2009       5.59        16.67       NaN
281   13-01-2009       5.57        16.82       NaN
282   14-01-2009        5.6        16.86       NaN
283   15-01-2009       5.62        16.97       NaN
284   16-01-2009       5.54        16.79       NaN
285   19-01-2009       5.54        16.81       NaN
286   20-01-2009       5.57        16.79       NaN
287   21-01-2009       5.57        16.71       NaN
288   22-01-2009       5.57        16.69       NaN
289   23-01-2009       5.56        16.73       NaN
290   26-01-2009       5.53        16.74       NaN
291   27-01-2009       5.47        16.76       NaN
292   28-01-2009        5.4         16.4       NaN
293   29-01-2009       5.38        16.22       NaN
294   30-01-2009       5.35        16.22       NaN
295   31-01-2009       5.31        16.26       NaN
296   02-02-2009       5.32         16.4       NaN
297   03-02-2009       5.31         16.3       NaN
298   04-02-2009       5.29        16.15       NaN
299   05-02-2009       5.28        16.13       NaN
300   06-02-2009       5.25        16.05       NaN
301   09-02-2009        5.2        15.98       NaN
302   10-02-2009       5.19        16.07       NaN
303   11-02-2009       5.16        16.17       NaN
304   12-02-2009       5.19        16.27       NaN
305   13-02-2009       5.19        16.21       NaN
306   16-02-2009       5.19        16.06       NaN
307   17-02-2009       5.23        16.45       NaN
308   18-02-2009       5.29        16.59       NaN
309   19-02-2009       5.31        16.48       NaN
310   20-02-2009       5.41        16.76       NaN
311   23-02-2009       5.44        16.85       NaN
312   24-02-2009       5.54        17.22       NaN
313   25-02-2009       5.54        17.17       NaN
314   26-02-2009       5.56        17.18       NaN
315   27-02-2009       5.58        17.39       NaN
316   28-02-2009       5.48        17.38       NaN
317   02-03-2009       5.56        17.84       NaN
318   03-03-2009       5.64        18.09       NaN
319   04-03-2009       5.75        18.28       NaN
320   05-03-2009       5.81        18.59       NaN
321   06-03-2009       5.87        18.66       NaN
322   09-03-2009       5.97        18.86       NaN
323   10-03-2009       5.99        18.71       NaN
324   11-03-2009          6        18.38       NaN
325   12-03-2009          6        18.29       NaN
326   13-03-2009          6        18.04       NaN
327   16-03-2009       5.96        17.63       NaN
328   17-03-2009       5.95        17.58       NaN
329   18-03-2009       5.97        17.97       NaN
330   19-03-2009       5.97        17.74       NaN
331   20-03-2009       5.99        17.74       NaN
332   23-03-2009       5.99        17.56       NaN
333   24-03-2009       5.98        17.45       NaN
334   25-03-2009          6        17.26       NaN
335   26-03-2009       5.98        17.09       NaN
336   27-03-2009       5.96        16.75       NaN
337   30-03-2009       5.99        16.89       NaN
338   31-03-2009       5.86        17.03       NaN
339   01-04-2009       5.86        17.12   85.9406
340   02-04-2009       5.82        16.78       NaN
341   03-04-2009       5.81        16.53       NaN
342   06-04-2009       5.78        16.43       NaN
343   07-04-2009       5.75        16.44       NaN
344   08-04-2009       5.71        16.36       NaN
345   09-04-2009       5.63        16.19       NaN
346   10-04-2009          .            .       NaN
347   13-04-2009        5.6        16.16       NaN
348   14-04-2009       5.54        15.85       NaN
349   15-04-2009       5.47        15.74       NaN
350   16-04-2009        5.4        15.44       NaN
351   17-04-2009       5.32        15.05       NaN
352   20-04-2009       5.28        15.17       NaN
353   21-04-2009       5.26        15.35       NaN
354   22-04-2009       5.23        15.27       NaN
355   23-04-2009        5.2        15.17       NaN
356   24-04-2009       5.16        14.87       NaN
357   27-04-2009       5.14        14.91       NaN
358   28-04-2009        5.1        14.79       NaN
359   29-04-2009       5.02        14.46       NaN
360   30-04-2009       4.87        13.45       NaN
361   01-05-2009       4.81        13.34   85.0635
362   04-05-2009       4.78        13.23       NaN
363   05-05-2009       4.71        13.08       NaN
364   06-05-2009       4.64        12.94       NaN
365   07-05-2009       4.53        12.54       NaN
366   08-05-2009       4.44        12.41       NaN
367   11-05-2009       4.44        12.58       NaN
368   12-05-2009       4.42        12.64       NaN
369   13-05-2009       4.42        12.85       NaN
370   14-05-2009       4.43        12.91       NaN
371   15-05-2009       4.42        12.91       NaN
372   18-05-2009        4.4        12.82       NaN
373   19-05-2009       4.34        12.67       NaN
374   20-05-2009       4.28        12.45       NaN
375   21-05-2009       4.25        12.32       NaN
376   22-05-2009       4.22        12.13       NaN
377   25-05-2009       4.22        12.15       NaN
378   26-05-2009       4.16        12.09       NaN
379   27-05-2009       4.09        11.87       NaN
380   28-05-2009       4.02        11.74       NaN
381   29-05-2009       3.94        11.76       NaN
382   31-05-2009       3.87         11.7       NaN
383   01-06-2009       3.82        11.36   84.7841
384   02-06-2009       3.71        11.19       NaN
385   03-06-2009       3.65        11.17       NaN
386   04-06-2009       3.63        11.01       NaN
387   05-06-2009       3.56         10.7       NaN
388   08-06-2009       3.52         10.6       NaN
389   09-06-2009        3.5        10.59       NaN
390   10-06-2009       3.44        10.42       NaN

In [160]:
df.dropna(inplace=True)
df = df[df.BAMLC0A0CM != '.']
df.reset_index(drop=True,inplace=True)

In [161]:
df

           DATE BAMLC0A0CM BAMLH0A0HYM2    INDPRO
0    01-02-2008        2.3         6.96  101.9384
1    01-04-2008       2.98         8.02  100.9098
2    01-05-2008       2.57         6.81  100.3073
3    01-07-2008       2.77         7.48   99.6124
4    01-08-2008          3         8.13   98.0601
5    01-09-2008       3.17         8.36   93.8451
6    01-10-2008       4.61        11.24   94.7036
7    01-12-2008       6.44         20.2   90.8250
8    01-04-2009       5.86        17.12   85.9406
9    01-05-2009       4.81        13.34   85.0635
10   01-06-2009       3.82        11.36   84.7841
11   01-07-2009       3.31         10.5   85.7471
12   01-09-2009       2.54         9.18   87.4072
13   01-10-2009       2.38         8.11   87.6595
14   01-12-2009       2.21         7.58   88.2819
15   01-02-2010       1.84         6.54   89.5648
16   01-03-2010       1.86         6.66   90.2296
17   01-04-2010       1.61         5.82   90.5689
18   01-06-2010       2.05         7.04   92.0070
19   01-07-2010       2.09         7.17   92.3967
20   01-09-2010       1.94          6.8   92.9252
21   01-10-2010       1.84         6.22   92.7115
22   01-11-2010       1.79         5.96   92.7535
23   01-12-2010       1.81         6.02   93.6492
24   01-02-2011       1.61         4.99   93.0617
25   01-03-2011       1.52         4.76   94.0244
26   01-04-2011        1.5         4.72   93.7011
27   01-06-2011       1.57         5.15   94.0844
28   01-07-2011       1.61         5.34   94.5881
29   01-08-2011       1.66         5.63   95.1605
30   01-09-2011        2.2         7.26   95.0855
31   01-11-2011       2.29         7.42   95.7307
32   01-12-2011       2.64         7.69   96.2047
33   01-02-2012       2.27         6.54   97.0510
34   01-03-2012       2.01         5.94   96.5714
35   01-05-2012       2.02         5.96   97.4669
36   01-06-2012       2.33         7.16   97.4577
37   01-08-2012       1.93          6.1   97.2842
38   01-10-2012       1.68         5.71   97.5344
39   01-11-2012        1.5         5.57   97.9837
40   01-02-2013       1.47         4.94   98.6458
41   01-03-2013       1.49            5   99.0597
42   01-04-2013       1.51         4.87   98.9927
43   01-05-2013       1.47          4.5   99.0726
44   01-07-2013       1.67         5.17   98.9204
45   01-08-2013       1.51         4.63   99.4996
46   01-10-2013       1.55         4.78   99.9168
47   01-11-2013       1.44         4.31  100.1762
48   01-04-2014       1.17         3.73  101.8337
49   01-05-2014       1.14         3.75  102.2325
50   01-07-2014       1.09          3.5  102.8479
51   01-08-2014       1.12         4.25  102.6491
52   01-09-2014       1.12         3.84  102.9858
53   01-10-2014       1.21         4.45  102.9911
54   01-12-2014       1.36         4.82  103.6139
55   01-04-2015       1.37         4.86  101.2859
56   01-05-2015       1.33         4.53  100.8408
57   01-06-2015       1.38         4.52  100.5063
58   01-07-2015       1.46         4.88  101.1831
59   01-09-2015        1.7         5.78  100.5680
60   01-10-2015       1.79         6.67  100.1588
61   01-12-2015       1.62          6.4   98.8329
62   01-02-2016       2.02         7.79   98.9583
63   01-03-2016       2.02         7.46   98.1954
64   01-04-2016       1.69         7.05   98.4673
65   01-06-2016       1.54         6.01   98.7201
66   01-07-2016       1.61         6.12   98.8992
67   01-08-2016        1.5         5.69   98.7249
68   01-09-2016       1.39         5.12   98.6060
69   01-11-2016       1.39         5.05   98.2288
70   01-12-2016       1.35         4.62   98.8958
71   01-02-2017       1.28         3.95   98.3676
72   01-03-2017       1.19         3.57   99.1065
73   01-05-2017       1.23         3.78  100.1470
74   01-06-2017       1.19         3.69  100.3042
75   01-08-2017       1.08          3.6   99.7055
76   01-09-2017       1.15         3.82   99.7485
77   01-11-2017       1.01         3.48  101.2730
78   01-12-2017       1.03         3.63  101.3696
79   01-02-2018        0.9         3.29  101.6495
80   01-03-2018       1.04         3.59  102.2980
81   01-05-2018       1.15         3.47  102.5408
82   01-06-2018       1.21         3.55  103.3045
83   01-08-2018       1.16         3.43  104.1659
84   01-10-2018       1.13         3.22  103.9874
85   01-11-2018       1.26         3.81  103.9127
86   01-02-2019       1.36         4.29  102.7280
87   01-03-2019       1.28         3.86  102.8635
88   01-04-2019       1.25         3.94  102.2543
89   01-05-2019       1.17         3.71  102.4519
90   01-07-2019       1.21         3.99  102.0568
91   01-08-2019       1.17          4.1  102.6882
92   01-10-2019       1.22         4.08  101.4645
93   01-11-2019       1.16         4.09  101.9876
94   01-04-2020       3.05         9.11   84.2018
95   01-05-2020       2.18          7.7   85.8434
96   01-06-2020       1.85         6.43   91.1622
97   01-07-2020       1.58         6.33   94.8887
98   01-09-2020       1.35         4.97   95.6019
99   01-10-2020       1.43         5.36   96.6454
100  01-12-2020       1.09         4.21   98.2854
101  01-02-2021       1.03         3.83   96.4433
102  01-03-2021       0.96         3.54   98.9318
103  01-04-2021       0.95         3.33   99.0174

In [162]:
df['Monthly Growth rate of IP'] = df['INDPRO'].pct_change(1)*100

<ipython-input-162-d5c364c7c1fa>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Monthly Growth rate of IP'] = df['INDPRO'].pct_change(1)*100

In [163]:
df.dropna(inplace=True)

<ipython-input-163-c64f9f573c18>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [164]:
df

           DATE BAMLC0A0CM BAMLH0A0HYM2    INDPRO  Monthly Growth rate of IP
1    01-04-2008       2.98         8.02  100.9098                  -1.009041
2    01-05-2008       2.57         6.81  100.3073                  -0.597068
3    01-07-2008       2.77         7.48   99.6124                  -0.692771
4    01-08-2008          3         8.13   98.0601                  -1.558340
5    01-09-2008       3.17         8.36   93.8451                  -4.298384
6    01-10-2008       4.61        11.24   94.7036                   0.914805
7    01-12-2008       6.44         20.2   90.8250                  -4.095515
8    01-04-2009       5.86        17.12   85.9406                  -5.377814
9    01-05-2009       4.81        13.34   85.0635                  -1.020589
10   01-06-2009       3.82        11.36   84.7841                  -0.328461
11   01-07-2009       3.31         10.5   85.7471                   1.135826
12   01-09-2009       2.54         9.18   87.4072                   1.936042
13   01-10-2009       2.38         8.11   87.6595                   0.288649
14   01-12-2009       2.21         7.58   88.2819                   0.710020
15   01-02-2010       1.84         6.54   89.5648                   1.453186
16   01-03-2010       1.86         6.66   90.2296                   0.742256
17   01-04-2010       1.61         5.82   90.5689                   0.376041
18   01-06-2010       2.05         7.04   92.0070                   1.587852
19   01-07-2010       2.09         7.17   92.3967                   0.423555
20   01-09-2010       1.94          6.8   92.9252                   0.571990
21   01-10-2010       1.84         6.22   92.7115                  -0.229970
22   01-11-2010       1.79         5.96   92.7535                   0.045302
23   01-12-2010       1.81         6.02   93.6492                   0.965678
24   01-02-2011       1.61         4.99   93.0617                  -0.627341
25   01-03-2011       1.52         4.76   94.0244                   1.034475
26   01-04-2011        1.5         4.72   93.7011                  -0.343847
27   01-06-2011       1.57         5.15   94.0844                   0.409067
28   01-07-2011       1.61         5.34   94.5881                   0.535370
29   01-08-2011       1.66         5.63   95.1605                   0.605150
30   01-09-2011        2.2         7.26   95.0855                  -0.078814
31   01-11-2011       2.29         7.42   95.7307                   0.678547
32   01-12-2011       2.64         7.69   96.2047                   0.495139
33   01-02-2012       2.27         6.54   97.0510                   0.879687
34   01-03-2012       2.01         5.94   96.5714                  -0.494173
35   01-05-2012       2.02         5.96   97.4669                   0.927293
36   01-06-2012       2.33         7.16   97.4577                  -0.009439
37   01-08-2012       1.93          6.1   97.2842                  -0.178026
38   01-10-2012       1.68         5.71   97.5344                   0.257185
39   01-11-2012        1.5         5.57   97.9837                   0.460658
40   01-02-2013       1.47         4.94   98.6458                   0.675725
41   01-03-2013       1.49            5   99.0597                   0.419582
42   01-04-2013       1.51         4.87   98.9927                  -0.067636
43   01-05-2013       1.47          4.5   99.0726                   0.080713
44   01-07-2013       1.67         5.17   98.9204                  -0.153625
45   01-08-2013       1.51         4.63   99.4996                   0.585521
46   01-10-2013       1.55         4.78   99.9168                   0.419298
47   01-11-2013       1.44         4.31  100.1762                   0.259616
48   01-04-2014       1.17         3.73  101.8337                   1.654585
49   01-05-2014       1.14         3.75  102.2325                   0.391619
50   01-07-2014       1.09          3.5  102.8479                   0.601961
51   01-08-2014       1.12         4.25  102.6491                  -0.193295
52   01-09-2014       1.12         3.84  102.9858                   0.328011
53   01-10-2014       1.21         4.45  102.9911                   0.005146
54   01-12-2014       1.36         4.82  103.6139                   0.604712
55   01-04-2015       1.37         4.86  101.2859                  -2.246803
56   01-05-2015       1.33         4.53  100.8408                  -0.439449
57   01-06-2015       1.38         4.52  100.5063                  -0.331711
58   01-07-2015       1.46         4.88  101.1831                   0.673391
59   01-09-2015        1.7         5.78  100.5680                  -0.607908
60   01-10-2015       1.79         6.67  100.1588                  -0.406889
61   01-12-2015       1.62          6.4   98.8329                  -1.323798
62   01-02-2016       2.02         7.79   98.9583                   0.126881
63   01-03-2016       2.02         7.46   98.1954                  -0.770931
64   01-04-2016       1.69         7.05   98.4673                   0.276897
65   01-06-2016       1.54         6.01   98.7201                   0.256735
66   01-07-2016       1.61         6.12   98.8992                   0.181422
67   01-08-2016        1.5         5.69   98.7249                  -0.176240
68   01-09-2016       1.39         5.12   98.6060                  -0.120436
69   01-11-2016       1.39         5.05   98.2288                  -0.382533
70   01-12-2016       1.35         4.62   98.8958                   0.679027
71   01-02-2017       1.28         3.95   98.3676                  -0.534098
72   01-03-2017       1.19         3.57   99.1065                   0.751162
73   01-05-2017       1.23         3.78  100.1470                   1.049881
74   01-06-2017       1.19         3.69  100.3042                   0.156969
75   01-08-2017       1.08          3.6   99.7055                  -0.596884
76   01-09-2017       1.15         3.82   99.7485                   0.043127
77   01-11-2017       1.01         3.48  101.2730                   1.528344
78   01-12-2017       1.03         3.63  101.3696                   0.095386
79   01-02-2018        0.9         3.29  101.6495                   0.276118
80   01-03-2018       1.04         3.59  102.2980                   0.637977
81   01-05-2018       1.15         3.47  102.5408                   0.237346
82   01-06-2018       1.21         3.55  103.3045                   0.744777
83   01-08-2018       1.16         3.43  104.1659                   0.833846
84   01-10-2018       1.13         3.22  103.9874                  -0.171361
85   01-11-2018       1.26         3.81  103.9127                  -0.071836
86   01-02-2019       1.36         4.29  102.7280                  -1.140092
87   01-03-2019       1.28         3.86  102.8635                   0.131902
88   01-04-2019       1.25         3.94  102.2543                  -0.592241
89   01-05-2019       1.17         3.71  102.4519                   0.193244
90   01-07-2019       1.21         3.99  102.0568                  -0.385644
91   01-08-2019       1.17          4.1  102.6882                   0.618675
92   01-10-2019       1.22         4.08  101.4645                  -1.191666
93   01-11-2019       1.16         4.09  101.9876                   0.515550
94   01-04-2020       3.05         9.11   84.2018                 -17.439179
95   01-05-2020       2.18          7.7   85.8434                   1.949602
96   01-06-2020       1.85         6.43   91.1622                   6.195934
97   01-07-2020       1.58         6.33   94.8887                   4.087769
98   01-09-2020       1.35         4.97   95.6019                   0.751617
99   01-10-2020       1.43         5.36   96.6454                   1.091506
100  01-12-2020       1.09         4.21   98.2854                   1.696925
101  01-02-2021       1.03         3.83   96.4433                  -1.874236
102  01-03-2021       0.96         3.54   98.9318                   2.580273
103  01-04-2021       0.95         3.33   99.0174                   0.086524

In [165]:
df.dtypes

DATE                          object
BAMLC0A0CM                    object
BAMLH0A0HYM2                  object
INDPRO                       float64
Monthly Growth rate of IP    float64
dtype: object

In [166]:
df['DATE'] = pd.to_datetime(df.DATE)

<ipython-input-166-94df645b1992>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DATE'] = pd.to_datetime(df.DATE)

In [167]:
df

          DATE BAMLC0A0CM BAMLH0A0HYM2    INDPRO  Monthly Growth rate of IP
1   2008-01-04       2.98         8.02  100.9098                  -1.009041
2   2008-01-05       2.57         6.81  100.3073                  -0.597068
3   2008-01-07       2.77         7.48   99.6124                  -0.692771
4   2008-01-08          3         8.13   98.0601                  -1.558340
5   2008-01-09       3.17         8.36   93.8451                  -4.298384
6   2008-01-10       4.61        11.24   94.7036                   0.914805
7   2008-01-12       6.44         20.2   90.8250                  -4.095515
8   2009-01-04       5.86        17.12   85.9406                  -5.377814
9   2009-01-05       4.81        13.34   85.0635                  -1.020589
10  2009-01-06       3.82        11.36   84.7841                  -0.328461
11  2009-01-07       3.31         10.5   85.7471                   1.135826
12  2009-01-09       2.54         9.18   87.4072                   1.936042
13  2009-01-10       2.38         8.11   87.6595                   0.288649
14  2009-01-12       2.21         7.58   88.2819                   0.710020
15  2010-01-02       1.84         6.54   89.5648                   1.453186
16  2010-01-03       1.86         6.66   90.2296                   0.742256
17  2010-01-04       1.61         5.82   90.5689                   0.376041
18  2010-01-06       2.05         7.04   92.0070                   1.587852
19  2010-01-07       2.09         7.17   92.3967                   0.423555
20  2010-01-09       1.94          6.8   92.9252                   0.571990
21  2010-01-10       1.84         6.22   92.7115                  -0.229970
22  2010-01-11       1.79         5.96   92.7535                   0.045302
23  2010-01-12       1.81         6.02   93.6492                   0.965678
24  2011-01-02       1.61         4.99   93.0617                  -0.627341
25  2011-01-03       1.52         4.76   94.0244                   1.034475
26  2011-01-04        1.5         4.72   93.7011                  -0.343847
27  2011-01-06       1.57         5.15   94.0844                   0.409067
28  2011-01-07       1.61         5.34   94.5881                   0.535370
29  2011-01-08       1.66         5.63   95.1605                   0.605150
30  2011-01-09        2.2         7.26   95.0855                  -0.078814
31  2011-01-11       2.29         7.42   95.7307                   0.678547
32  2011-01-12       2.64         7.69   96.2047                   0.495139
33  2012-01-02       2.27         6.54   97.0510                   0.879687
34  2012-01-03       2.01         5.94   96.5714                  -0.494173
35  2012-01-05       2.02         5.96   97.4669                   0.927293
36  2012-01-06       2.33         7.16   97.4577                  -0.009439
37  2012-01-08       1.93          6.1   97.2842                  -0.178026
38  2012-01-10       1.68         5.71   97.5344                   0.257185
39  2012-01-11        1.5         5.57   97.9837                   0.460658
40  2013-01-02       1.47         4.94   98.6458                   0.675725
41  2013-01-03       1.49            5   99.0597                   0.419582
42  2013-01-04       1.51         4.87   98.9927                  -0.067636
43  2013-01-05       1.47          4.5   99.0726                   0.080713
44  2013-01-07       1.67         5.17   98.9204                  -0.153625
45  2013-01-08       1.51         4.63   99.4996                   0.585521
46  2013-01-10       1.55         4.78   99.9168                   0.419298
47  2013-01-11       1.44         4.31  100.1762                   0.259616
48  2014-01-04       1.17         3.73  101.8337                   1.654585
49  2014-01-05       1.14         3.75  102.2325                   0.391619
50  2014-01-07       1.09          3.5  102.8479                   0.601961
51  2014-01-08       1.12         4.25  102.6491                  -0.193295
52  2014-01-09       1.12         3.84  102.9858                   0.328011
53  2014-01-10       1.21         4.45  102.9911                   0.005146
54  2014-01-12       1.36         4.82  103.6139                   0.604712
55  2015-01-04       1.37         4.86  101.2859                  -2.246803
56  2015-01-05       1.33         4.53  100.8408                  -0.439449
57  2015-01-06       1.38         4.52  100.5063                  -0.331711
58  2015-01-07       1.46         4.88  101.1831                   0.673391
59  2015-01-09        1.7         5.78  100.5680                  -0.607908
60  2015-01-10       1.79         6.67  100.1588                  -0.406889
61  2015-01-12       1.62          6.4   98.8329                  -1.323798
62  2016-01-02       2.02         7.79   98.9583                   0.126881
63  2016-01-03       2.02         7.46   98.1954                  -0.770931
64  2016-01-04       1.69         7.05   98.4673                   0.276897
65  2016-01-06       1.54         6.01   98.7201                   0.256735
66  2016-01-07       1.61         6.12   98.8992                   0.181422
67  2016-01-08        1.5         5.69   98.7249                  -0.176240
68  2016-01-09       1.39         5.12   98.6060                  -0.120436
69  2016-01-11       1.39         5.05   98.2288                  -0.382533
70  2016-01-12       1.35         4.62   98.8958                   0.679027
71  2017-01-02       1.28         3.95   98.3676                  -0.534098
72  2017-01-03       1.19         3.57   99.1065                   0.751162
73  2017-01-05       1.23         3.78  100.1470                   1.049881
74  2017-01-06       1.19         3.69  100.3042                   0.156969
75  2017-01-08       1.08          3.6   99.7055                  -0.596884
76  2017-01-09       1.15         3.82   99.7485                   0.043127
77  2017-01-11       1.01         3.48  101.2730                   1.528344
78  2017-01-12       1.03         3.63  101.3696                   0.095386
79  2018-01-02        0.9         3.29  101.6495                   0.276118
80  2018-01-03       1.04         3.59  102.2980                   0.637977
81  2018-01-05       1.15         3.47  102.5408                   0.237346
82  2018-01-06       1.21         3.55  103.3045                   0.744777
83  2018-01-08       1.16         3.43  104.1659                   0.833846
84  2018-01-10       1.13         3.22  103.9874                  -0.171361
85  2018-01-11       1.26         3.81  103.9127                  -0.071836
86  2019-01-02       1.36         4.29  102.7280                  -1.140092
87  2019-01-03       1.28         3.86  102.8635                   0.131902
88  2019-01-04       1.25         3.94  102.2543                  -0.592241
89  2019-01-05       1.17         3.71  102.4519                   0.193244
90  2019-01-07       1.21         3.99  102.0568                  -0.385644
91  2019-01-08       1.17          4.1  102.6882                   0.618675
92  2019-01-10       1.22         4.08  101.4645                  -1.191666
93  2019-01-11       1.16         4.09  101.9876                   0.515550
94  2020-01-04       3.05         9.11   84.2018                 -17.439179
95  2020-01-05       2.18          7.7   85.8434                   1.949602
96  2020-01-06       1.85         6.43   91.1622                   6.195934
97  2020-01-07       1.58         6.33   94.8887                   4.087769
98  2020-01-09       1.35         4.97   95.6019                   0.751617
99  2020-01-10       1.43         5.36   96.6454                   1.091506
100 2020-01-12       1.09         4.21   98.2854                   1.696925
101 2021-01-02       1.03         3.83   96.4433                  -1.874236
102 2021-01-03       0.96         3.54   98.9318                   2.580273
103 2021-01-04       0.95         3.33   99.0174                   0.086524

In [129]:
df['DATE'] = df['DATE'].dt.strftime('%Y-%m-%d')

<ipython-input-129-a5c93c944d40>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DATE'] = df['DATE'].dt.strftime('%Y-%m-%d')

In [168]:
df['DATE'].apply(lambda dt: dt.replace(day=31))

1     2008-01-31
2     2008-01-31
3     2008-01-31
4     2008-01-31
5     2008-01-31
6     2008-01-31
7     2008-01-31
8     2009-01-31
9     2009-01-31
10    2009-01-31
11    2009-01-31
12    2009-01-31
13    2009-01-31
14    2009-01-31
15    2010-01-31
16    2010-01-31
17    2010-01-31
18    2010-01-31
19    2010-01-31
20    2010-01-31
21    2010-01-31
22    2010-01-31
23    2010-01-31
24    2011-01-31
25    2011-01-31
26    2011-01-31
27    2011-01-31
28    2011-01-31
29    2011-01-31
30    2011-01-31
31    2011-01-31
32    2011-01-31
33    2012-01-31
34    2012-01-31
35    2012-01-31
36    2012-01-31
37    2012-01-31
38    2012-01-31
39    2012-01-31
40    2013-01-31
41    2013-01-31
42    2013-01-31
43    2013-01-31
44    2013-01-31
45    2013-01-31
46    2013-01-31
47    2013-01-31
48    2014-01-31
49    2014-01-31
50    2014-01-31
51    2014-01-31
52    2014-01-31
53    2014-01-31
54    2014-01-31
55    2015-01-31
56    2015-01-31
57    2015-01-31
58    2015-01-31
59    2015-01-31
60    2015-01-31
61    2015-01-31
62    2016-01-31
63    2016-01-31
64    2016-01-31
65    2016-01-31
66    2016-01-31
67    2016-01-31
68    2016-01-31
69    2016-01-31
70    2016-01-31
71    2017-01-31
72    2017-01-31
73    2017-01-31
74    2017-01-31
75    2017-01-31
76    2017-01-31
77    2017-01-31
78    2017-01-31
79    2018-01-31
80    2018-01-31
81    2018-01-31
82    2018-01-31
83    2018-01-31
84    2018-01-31
85    2018-01-31
86    2019-01-31
87    2019-01-31
88    2019-01-31
89    2019-01-31
90    2019-01-31
91    2019-01-31
92    2019-01-31
93    2019-01-31
94    2020-01-31
95    2020-01-31
96    2020-01-31
97    2020-01-31
98    2020-01-31
99    2020-01-31
100   2020-01-31
101   2021-01-31
102   2021-01-31
103   2021-01-31
Name: DATE, dtype: datetime64[ns]

In [137]:
df

          DATE BAMLC0A0CM BAMLH0A0HYM2    INDPRO  Monthly Growth rate of IP
1   2008-01-04       2.98         8.02  100.9098                  -1.009041
2   2008-01-05       2.57         6.81  100.3073                  -0.597068
3   2008-01-07       2.77         7.48   99.6124                  -0.692771
4   2008-01-08          3         8.13   98.0601                  -1.558340
5   2008-01-09       3.17         8.36   93.8451                  -4.298384
6   2008-01-10       4.61        11.24   94.7036                   0.914805
7   2008-01-12       6.44         20.2   90.8250                  -4.095515
8   2009-01-04       5.86        17.12   85.9406                  -5.377814
9   2009-01-05       4.81        13.34   85.0635                  -1.020589
10  2009-01-06       3.82        11.36   84.7841                  -0.328461
11  2009-01-07       3.31         10.5   85.7471                   1.135826
12  2009-01-09       2.54         9.18   87.4072                   1.936042
13  2009-01-10       2.38         8.11   87.6595                   0.288649
14  2009-01-12       2.21         7.58   88.2819                   0.710020
15  2010-01-02       1.84         6.54   89.5648                   1.453186
16  2010-01-03       1.86         6.66   90.2296                   0.742256
17  2010-01-04       1.61         5.82   90.5689                   0.376041
18  2010-01-06       2.05         7.04   92.0070                   1.587852
19  2010-01-07       2.09         7.17   92.3967                   0.423555
20  2010-01-09       1.94          6.8   92.9252                   0.571990
21  2010-01-10       1.84         6.22   92.7115                  -0.229970
22  2010-01-11       1.79         5.96   92.7535                   0.045302
23  2010-01-12       1.81         6.02   93.6492                   0.965678
24  2011-01-02       1.61         4.99   93.0617                  -0.627341
25  2011-01-03       1.52         4.76   94.0244                   1.034475
26  2011-01-04        1.5         4.72   93.7011                  -0.343847
27  2011-01-06       1.57         5.15   94.0844                   0.409067
28  2011-01-07       1.61         5.34   94.5881                   0.535370
29  2011-01-08       1.66         5.63   95.1605                   0.605150
30  2011-01-09        2.2         7.26   95.0855                  -0.078814
31  2011-01-11       2.29         7.42   95.7307                   0.678547
32  2011-01-12       2.64         7.69   96.2047                   0.495139
33  2012-01-02       2.27         6.54   97.0510                   0.879687
34  2012-01-03       2.01         5.94   96.5714                  -0.494173
35  2012-01-05       2.02         5.96   97.4669                   0.927293
36  2012-01-06       2.33         7.16   97.4577                  -0.009439
37  2012-01-08       1.93          6.1   97.2842                  -0.178026
38  2012-01-10       1.68         5.71   97.5344                   0.257185
39  2012-01-11        1.5         5.57   97.9837                   0.460658
40  2013-01-02       1.47         4.94   98.6458                   0.675725
41  2013-01-03       1.49            5   99.0597                   0.419582
42  2013-01-04       1.51         4.87   98.9927                  -0.067636
43  2013-01-05       1.47          4.5   99.0726                   0.080713
44  2013-01-07       1.67         5.17   98.9204                  -0.153625
45  2013-01-08       1.51         4.63   99.4996                   0.585521
46  2013-01-10       1.55         4.78   99.9168                   0.419298
47  2013-01-11       1.44         4.31  100.1762                   0.259616
48  2014-01-04       1.17         3.73  101.8337                   1.654585
49  2014-01-05       1.14         3.75  102.2325                   0.391619
50  2014-01-07       1.09          3.5  102.8479                   0.601961
51  2014-01-08       1.12         4.25  102.6491                  -0.193295
52  2014-01-09       1.12         3.84  102.9858                   0.328011
53  2014-01-10       1.21         4.45  102.9911                   0.005146
54  2014-01-12       1.36         4.82  103.6139                   0.604712
55  2015-01-04       1.37         4.86  101.2859                  -2.246803
56  2015-01-05       1.33         4.53  100.8408                  -0.439449
57  2015-01-06       1.38         4.52  100.5063                  -0.331711
58  2015-01-07       1.46         4.88  101.1831                   0.673391
59  2015-01-09        1.7         5.78  100.5680                  -0.607908
60  2015-01-10       1.79         6.67  100.1588                  -0.406889
61  2015-01-12       1.62          6.4   98.8329                  -1.323798
62  2016-01-02       2.02         7.79   98.9583                   0.126881
63  2016-01-03       2.02         7.46   98.1954                  -0.770931
64  2016-01-04       1.69         7.05   98.4673                   0.276897
65  2016-01-06       1.54         6.01   98.7201                   0.256735
66  2016-01-07       1.61         6.12   98.8992                   0.181422
67  2016-01-08        1.5         5.69   98.7249                  -0.176240
68  2016-01-09       1.39         5.12   98.6060                  -0.120436
69  2016-01-11       1.39         5.05   98.2288                  -0.382533
70  2016-01-12       1.35         4.62   98.8958                   0.679027
71  2017-01-02       1.28         3.95   98.3676                  -0.534098
72  2017-01-03       1.19         3.57   99.1065                   0.751162
73  2017-01-05       1.23         3.78  100.1470                   1.049881
74  2017-01-06       1.19         3.69  100.3042                   0.156969
75  2017-01-08       1.08          3.6   99.7055                  -0.596884
76  2017-01-09       1.15         3.82   99.7485                   0.043127
77  2017-01-11       1.01         3.48  101.2730                   1.528344
78  2017-01-12       1.03         3.63  101.3696                   0.095386
79  2018-01-02        0.9         3.29  101.6495                   0.276118
80  2018-01-03       1.04         3.59  102.2980                   0.637977
81  2018-01-05       1.15         3.47  102.5408                   0.237346
82  2018-01-06       1.21         3.55  103.3045                   0.744777
83  2018-01-08       1.16         3.43  104.1659                   0.833846
84  2018-01-10       1.13         3.22  103.9874                  -0.171361
85  2018-01-11       1.26         3.81  103.9127                  -0.071836
86  2019-01-02       1.36         4.29  102.7280                  -1.140092
87  2019-01-03       1.28         3.86  102.8635                   0.131902
88  2019-01-04       1.25         3.94  102.2543                  -0.592241
89  2019-01-05       1.17         3.71  102.4519                   0.193244
90  2019-01-07       1.21         3.99  102.0568                  -0.385644
91  2019-01-08       1.17          4.1  102.6882                   0.618675
92  2019-01-10       1.22         4.08  101.4645                  -1.191666
93  2019-01-11       1.16         4.09  101.9876                   0.515550
94  2020-01-04       3.05         9.11   84.2018                 -17.439179
95  2020-01-05       2.18          7.7   85.8434                   1.949602
96  2020-01-06       1.85         6.43   91.1622                   6.195934
97  2020-01-07       1.58         6.33   94.8887                   4.087769
98  2020-01-09       1.35         4.97   95.6019                   0.751617
99  2020-01-10       1.43         5.36   96.6454                   1.091506
100 2020-01-12       1.09         4.21   98.2854                   1.696925
101 2021-01-02       1.03         3.83   96.4433                  -1.874236
102 2021-01-03       0.96         3.54   98.9318                   2.580273
103 2021-01-04       0.95         3.33   99.0174                   0.086524

In [169]:
df['DATE'].dt

AttributeError: 'DatetimeProperties' object has no attribute 'replace'

In [170]:
df['DATE'].dt.s

1      2008-01-04
2      2008-01-05
3      2008-01-07
4      2008-01-08
5      2008-01-09
6      2008-01-10
7      2008-01-12
8      2009-01-04
9      2009-01-05
10     2009-01-06
11     2009-01-07
12     2009-01-09
13     2009-01-10
14     2009-01-12
15     2010-01-02
16     2010-01-03
17     2010-01-04
18     2010-01-06
19     2010-01-07
20     2010-01-09
21     2010-01-10
22     2010-01-11
23     2010-01-12
24     2011-01-02
25     2011-01-03
26     2011-01-04
27     2011-01-06
28     2011-01-07
29     2011-01-08
30     2011-01-09
31     2011-01-11
32     2011-01-12
33     2012-01-02
34     2012-01-03
35     2012-01-05
36     2012-01-06
37     2012-01-08
38     2012-01-10
39     2012-01-11
40     2013-01-02
41     2013-01-03
42     2013-01-04
43     2013-01-05
44     2013-01-07
45     2013-01-08
46     2013-01-10
47     2013-01-11
48     2014-01-04
49     2014-01-05
50     2014-01-07
51     2014-01-08
52     2014-01-09
53     2014-01-10
54     2014-01-12
55     2015-01-04
56     2015-01-05
57     2015-01-06
58     2015-01-07
59     2015-01-09
60     2015-01-10
61     2015-01-12
62     2016-01-02
63     2016-01-03
64     2016-01-04
65     2016-01-06
66     2016-01-07
67     2016-01-08
68     2016-01-09
69     2016-01-11
70     2016-01-12
71     2017-01-02
72     2017-01-03
73     2017-01-05
74     2017-01-06
75     2017-01-08
76     2017-01-09
77     2017-01-11
78     2017-01-12
79     2018-01-02
80     2018-01-03
81     2018-01-05
82     2018-01-06
83     2018-01-08
84     2018-01-10
85     2018-01-11
86     2019-01-02
87     2019-01-03
88     2019-01-04
89     2019-01-05
90     2019-01-07
91     2019-01-08
92     2019-01-10
93     2019-01-11
94     2020-01-04
95     2020-01-05
96     2020-01-06
97     2020-01-07
98     2020-01-09
99     2020-01-10
100    2020-01-12
101    2021-01-02
102    2021-01-03
103    2021-01-04
Name: DATE, dtype: object