In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [60]:
dataset = pd.read_csv('train.csv')

In [72]:
pd.set_option('display.max_columns', 35)
dataset

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,F16,F17,F18,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28,outcome
0,35,2,32,1,1,1,1,2,1,1,4621,4646359,11,151135,73,84,115,108,49,88,59,28,37396,26132,339327,460243,337225,3,1
1,49,1,29,1,1,2,1,1,2,2,6928,4711988,14,206506,87,43,107,52,85,91,82,35,79325,1082472,5,5,5,9,2
2,33,2,27,2,2,1,2,1,1,1,7666,4137761,12,110251,113,94,52,86,110,76,76,33,1108530,128916,174314,315957,427125,6,2
3,32,2,35,2,2,2,1,1,1,1,10240,4953619,15,107047,65,126,117,51,109,85,39,36,20495,854154,646250,435109,243221,6,2
4,49,1,23,2,2,1,2,2,1,1,4542,4670848,10,180843,75,90,45,116,42,119,101,39,916829,644084,29920,264492,364452,9,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,55,1,30,2,2,2,1,2,1,1,9369,4259591,14,111018,115,61,39,115,40,43,68,36,1146286,103732,651970,44514,312828,12,4
1034,34,1,28,2,1,2,2,1,2,1,11951,4679689,15,120161,66,77,114,62,128,117,123,34,735499,669834,187088,302106,262297,6,3
1035,51,2,28,2,1,2,2,2,1,1,6448,3921586,12,105382,51,73,60,43,69,87,70,30,274534,291553,5,5,5,16,2
1036,41,1,34,2,2,2,2,2,2,1,7376,3932014,15,149153,79,64,86,123,54,105,39,34,368929,871981,330284,335217,192369,11,1
1037,51,2,35,1,1,1,1,2,1,2,5828,4782262,13,196623,90,119,117,57,77,115,99,41,757756,87029,5,5,5,9,1

In [68]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [69]:
# library for one hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# [1] represent column number which you want to encode
# Product Container is the 1st column (index starts from zero) in the dataset 
transform = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(transform.fit_transform(X), dtype = np.str)

In [79]:
transform = ColumnTransformer([('encoder', OneHotEncoder(), [4])], remainder='passthrough')
X = np.array(transform.fit_transform(X), dtype = np.str)

In [81]:
transform = ColumnTransformer([('encoder', OneHotEncoder(), [6])], remainder='passthrough')
X = np.array(transform.fit_transform(X), dtype = np.str)

In [83]:
transform = ColumnTransformer([('encoder', OneHotEncoder(), [8])], remainder='passthrough')
X = np.array(transform.fit_transform(X), dtype = np.str)

In [85]:
transform = ColumnTransformer([('encoder', OneHotEncoder(), [10])], remainder='passthrough')
X = np.array(transform.fit_transform(X), dtype = np.str)

In [87]:
transform = ColumnTransformer([('encoder', OneHotEncoder(), [12])], remainder='passthrough')
X = np.array(transform.fit_transform(X), dtype = np.str)

In [89]:
transform = ColumnTransformer([('encoder', OneHotEncoder(), [14])], remainder='passthrough')
X = np.array(transform.fit_transform(X), dtype = np.str)

In [91]:
transform = ColumnTransformer([('encoder', OneHotEncoder(), [16])], remainder='passthrough')
X = np.array(transform.fit_transform(X), dtype = np.str)

In [93]:
X

array([['1.0', '0.0', '1.0', ..., '460243.0', '337225.0', '3.0'],
       ['0.0', '1.0', '0.0', ..., '5.0', '5.0', '9.0'],
       ['1.0', '0.0', '1.0', ..., '315957.0', '427125.0', '6.0'],
       ...,
       ['1.0', '0.0', '1.0', ..., '5.0', '5.0', '16.0'],
       ['1.0', '0.0', '0.0', ..., '335217.0', '192369.0', '11.0'],
       ['0.0', '1.0', '1.0', ..., '5.0', '5.0', '9.0']], dtype='<U32')

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0, random_state = 0)

ValueError: test_size=0 should be either positive and smaller than the number of samples 1038 or a float in the (0, 1) range

In [94]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X)
# X_test = sc.transform(X)

In [178]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 500, metric = 'minkowski', p = 2)
classifier.fit(X_train, y)

KNeighborsClassifier(n_neighbors=500)

In [179]:
scoring = 'accuracy'
from sklearn.model_selection import KFold, cross_validate,StratifiedKFold

In [180]:
kf = StratifiedKFold(n_splits=5, shuffle=True)

In [181]:
cv_results = cross_validate(classifier, X, y, cv=kf, scoring=scoring, return_train_score=True)
cv_results

C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)

C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)
C:\Users\avitr\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  return f(**kwargs)

{'fit_time': array([0.00449967, 0.00804186, 0.00800014, 0.00547338, 0.00247335]),
 'score_time': array([0.21239996, 0.10108352, 0.08789563, 0.09822822, 0.10054064]),
 'test_score': array([0.25961538, 0.30769231, 0.29326923, 0.28502415, 0.20772947]),
 'train_score': array([0.28192771, 0.26987952, 0.28554217, 0.26113117, 0.29843562])}

In [182]:
from sklearn.model_selection import cross_validate

In [10]:
cv_results = cross_validate(lasso, X, y, cv=3)

NameError: name 'lasso' is not defined