# 4.1

In [1]:
# Loading data:
# Import function for loading the 'boston' dataset.
from sklearn.datasets import load_boston
# Load a 'bunch' containing data and descriptions.
boston_bunch = load_boston()
# Extract and store predictor variables.
X = boston_bunch.data
# Extract and store the variable that is the target for prediction.
y = boston_bunch.target
# Extract and store labels of predictor variables.
labels = boston_bunch.feature_names

In [2]:
# import the library
import pandas as pd

# get the dataframe from X for better understanding.
df = pd.DataFrame(X,columns=labels)
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [3]:
# create a new column 'MEDV' and assign y
df['MEDV'] = y
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [4]:
# split the dataset
# 67% for training set and 33% for test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.33, random_state = 553)

# 4.2

In [5]:
# import the library for OLS and r-square
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# model #1

In [6]:
# build the OLS model
model_1 = LinearRegression()

# fit the data
model_1.fit(X_train,y_train)

#predictions on training data
y_pred_train_1 = model_1.predict(X_train) 

#predictions on test data
y_pred_test_1 = model_1.predict(X_test)

# model #2

In [7]:
# since you need to use only AGE, NOX, DIS, and RAD column
# so get their index i.e. 6,4,7,8
labels

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [8]:
# get the training and test data 
X_train_new = X_train[:,[6,4,7,8]]
X_test_new = X_test[:,[6,4,7,8]]

In [9]:
# build the OLS model and fit the data
model_2 = LinearRegression()
model_2.fit(X_train_new,y_train)
y_pred_train_2 = model_2.predict(X_train_new) #predictions on training data
y_pred_test_2 = model_2.predict(X_test_new)   #predictions on test data

# model# 3

In [10]:
from sklearn.preprocessing import PolynomialFeatures

# Generate polynomial and interaction features
poly_reg = PolynomialFeatures(degree = 2)

# Fit to data, then transform it
X_train_poly = poly_reg.fit_transform(X_train)

# build the model
model_3 = LinearRegression()

# fit the polynomial features
model_3.fit(X_train_poly, y_train)

# get predictions for training and test set
y_pred_train_3 = model_3.predict(poly_reg.fit_transform(X_train))
y_pred_test_3 = model_3.predict(poly_reg.fit_transform(X_test))

# 4.3

# Model 1

In [11]:
print('The R^2 of the predictions on the training set:',r2_score(y_train, y_pred_train_1))
print('The R^2 of the predictions on the test set:',r2_score(y_test, y_pred_test_1))

print('TRUE_MEDV:',y_test[:5])
print('PRED_MEDV:',y_pred_test_1[:5])

The R^2 of the predictions on the training set: 0.7679628381299844
The R^2 of the predictions on the test set: 0.6848940888411765
TRUE_MEDV: [24.6  5.6 27.1 21.9 20. ]
PRED_MEDV: [24.25726341 12.11009855 27.68460646 24.1247323  21.84676907]

# Model 2

In [12]:
print('The R^2 of the predictions on the training set:',r2_score(y_train, y_pred_train_2))
print('The R^2 of the predictions on the test set:',r2_score(y_test, y_pred_test_2))

print('TRUE_MEDV:',y_test[:5])
print('PRED_MEDV:',y_pred_test_2[:5])

The R^2 of the predictions on the training set: 0.28125855252798593
The R^2 of the predictions on the test set: 0.1863295969882507
TRUE_MEDV: [24.6  5.6 27.1 21.9 20. ]
PRED_MEDV: [27.98320109 15.51317765 25.38341437 24.12187893 26.39505681]

# Model 3

In [13]:
print('The R^2 of the predictions on the training set:',r2_score(y_train, y_pred_train_3))
print('The R^2 of the predictions on the test set:',r2_score(y_test, y_pred_test_3))

print('TRUE_MEDV:',y_test[:5])
print('PRED_MEDV:',y_pred_test_3[:5])

The R^2 of the predictions on the training set: 0.9425328444439955
The R^2 of the predictions on the test set: 0.8258937549100432
TRUE_MEDV: [24.6  5.6 27.1 21.9 20. ]
PRED_MEDV: [26.31024152  6.62266335 28.09554833 19.676503   21.88080508]

# 4.4

- Since,higher R-square indicates a better fit for the model. Therefore based on the R-square values of three models. It is safe to assume that model 3 is the best. It has highest R-square value on training (0.9425) and test set(0.8258).

In [ ]:
Assume that we have a floating point format with the first bit as the sign bit,
the next 5 bits as the exponent bits (with a bias of 15), and then 5 bits as the significand. 
Write down the binary format for two decimal numbers A=15.25 and B=1.375. 
Do binary arithmetic for A+B, A*B and A/B and check your results with results from demical 
arithmetic.