In [1]:
# read the file
with open('RealEstateData.txt', 'r') as file:
    em_data = file.readlines()

In [2]:
# extract the price column and store in prices list
prices = [i.strip().split()[0] for i in em_data if i.strip()!='']

In [3]:
prices

['599000',
 '517000',
 '396000',
 '558000',
 '496000',
 '464000',
 '413000',
 '505000',
 '577000',
 '572000',
 '485000',
 '554000',
 '334000',
 '306000',
 '434000',
 '480000',
 '400000',
 '449000',
 '454000',
 '593000',
 '338000',
 '376000',
 '521000',
 '523000',
 '518000',
 '351000',
 '429000',
 '428000',
 '488000',
 '488000',
 '553000',
 '359000',
 '419000',
 '455000',
 '611000',
 '280000',
 '364000',
 '551000',
 '347000',
 '469000',
 '427000',
 '443000',
 '501000',
 '302000',
 '461000',
 '469000',
 '631000',
 '335000',
 '357000',
 '540000',
 '309000',
 '263000',
 '322000',
 '376000',
 '399000',
 '286000',
 '280000',
 '330000',
 '592000',
 '412000',
 '455000',
 '406000',
 '470000',
 '386000',
 '513000',
 '372000',
 '515000',
 '566000',
 '479000',
 '513000',
 '481000',
 '606000',
 '378000',
 '575000',
 '360000',
 '617000',
 '533000',
 '408000',
 '575000',
 '511000',
 '478000',
 '425000',
 '520000',
 '594000',
 '589000',
 '500000',
 '571000',
 '344000',
 '315000',
 '447000',
 '494000',
 '412000',
 '462000',
 '468000',
 '611000',
 '348000',
 '387000',
 '537000',
 '539000',
 '534000',
 '362000',
 '442000',
 '441000',
 '503000',
 '503000',
 '570000',
 '370000',
 '432000',
 '469000',
 '629000',
 '288000',
 '375000',
 '568000',
 '357000',
 '483000',
 '440000',
 '456000',
 '516000',
 '311000',
 '475000',
 '483000',
 '650000',
 '345000',
 '368000',
 '556000',
 '318000',
 '271000',
 '332000',
 '387000',
 '411000',
 '295000',
 '288000',
 '340000',
 '610000',
 '424000',
 '469000',
 '418000',
 '484000',
 '398000',
 '528000',
 '383000',
 '530000',
 '583000',
 '493000',
 '528000',
 '495000',
 '624000',
 '389000',
 '592000',
 '371000',
 '539000',
 '465000',
 '356000',
 '502000',
 '446000',
 '418000',
 '372000',
 '455000',
 '519000',
 '515000',
 '437000',
 '499000',
 '301000',
 '275000',
 '391000',
 '432000',
 '360000',
 '404000',
 '409000',
 '534000',
 '304000',
 '338000',
 '469000',
 '471000',
 '466000',
 '316000',
 '386000',
 '385000',
 '439000',
 '439000',
 '498000',
 '323000',
 '377000',
 '410000',
 '550000',
 '252000',
 '328000',
 '496000',
 '312000',
 '422000',
 '384000',
 '399000',
 '451000',
 '272000',
 '415000',
 '422000',
 '568000',
 '302000',
 '321000',
 '486000',
 '278000',
 '237000',
 '290000',
 '338000',
 '359000',
 '257000',
 '252000',
 '297000',
 '533000',
 '371000',
 '410000',
 '365000',
 '423000',
 '347000',
 '462000',
 '335000',
 '464000',
 '509000',
 '431000',
 '462000',
 '433000',
 '545000',
 '340000',
 '518000',
 '324000',
 '749000',
 '646000',
 '495000',
 '698000',
 '620000',
 '580000',
 '516000',
 '631000',
 '721000',
 '715000',
 '606000',
 '693000',
 '418000',
 '383000',
 '543000',
 '600000',
 '500000',
 '561000',
 '568000',
 '741000',
 '423000',
 '470000',
 '651000',
 '654000',
 '648000',
 '439000',
 '536000',
 '535000',
 '610000',
 '610000',
 '691000',
 '449000',
 '524000',
 '569000',
 '764000',
 '350000',
 '455000',
 '689000',
 '434000',
 '586000',
 '534000',
 '554000',
 '626000',
 '378000',
 '576000',
 '586000',
 '789000',
 '419000',
 '446000',
 '675000',
 '386000',
 '329000',
 '403000',
 '470000',
 '499000',
 '358000',
 '350000',
 '413000',
 '740000',
 '515000',
 '569000',
 '508000',
 '588000',
 '483000',
 '641000',
 '465000',
 '644000',
 '708000',
 '599000',
 '641000',
 '601000',
 '758000',
 '473000',
 '719000',
 '450000']

In [4]:
# as the price is in string form,convert it to int 
print('Before conversion: ',type(prices[0]))
prices = [int(price) for price in prices]
print('After conversion: ',type(prices[0]))

Before conversion:  <class 'str'>
After conversion:  <class 'int'>

In [5]:
# now all the price is in integer form
prices

[599000,
 517000,
 396000,
 558000,
 496000,
 464000,
 413000,
 505000,
 577000,
 572000,
 485000,
 554000,
 334000,
 306000,
 434000,
 480000,
 400000,
 449000,
 454000,
 593000,
 338000,
 376000,
 521000,
 523000,
 518000,
 351000,
 429000,
 428000,
 488000,
 488000,
 553000,
 359000,
 419000,
 455000,
 611000,
 280000,
 364000,
 551000,
 347000,
 469000,
 427000,
 443000,
 501000,
 302000,
 461000,
 469000,
 631000,
 335000,
 357000,
 540000,
 309000,
 263000,
 322000,
 376000,
 399000,
 286000,
 280000,
 330000,
 592000,
 412000,
 455000,
 406000,
 470000,
 386000,
 513000,
 372000,
 515000,
 566000,
 479000,
 513000,
 481000,
 606000,
 378000,
 575000,
 360000,
 617000,
 533000,
 408000,
 575000,
 511000,
 478000,
 425000,
 520000,
 594000,
 589000,
 500000,
 571000,
 344000,
 315000,
 447000,
 494000,
 412000,
 462000,
 468000,
 611000,
 348000,
 387000,
 537000,
 539000,
 534000,
 362000,
 442000,
 441000,
 503000,
 503000,
 570000,
 370000,
 432000,
 469000,
 629000,
 288000,
 375000,
 568000,
 357000,
 483000,
 440000,
 456000,
 516000,
 311000,
 475000,
 483000,
 650000,
 345000,
 368000,
 556000,
 318000,
 271000,
 332000,
 387000,
 411000,
 295000,
 288000,
 340000,
 610000,
 424000,
 469000,
 418000,
 484000,
 398000,
 528000,
 383000,
 530000,
 583000,
 493000,
 528000,
 495000,
 624000,
 389000,
 592000,
 371000,
 539000,
 465000,
 356000,
 502000,
 446000,
 418000,
 372000,
 455000,
 519000,
 515000,
 437000,
 499000,
 301000,
 275000,
 391000,
 432000,
 360000,
 404000,
 409000,
 534000,
 304000,
 338000,
 469000,
 471000,
 466000,
 316000,
 386000,
 385000,
 439000,
 439000,
 498000,
 323000,
 377000,
 410000,
 550000,
 252000,
 328000,
 496000,
 312000,
 422000,
 384000,
 399000,
 451000,
 272000,
 415000,
 422000,
 568000,
 302000,
 321000,
 486000,
 278000,
 237000,
 290000,
 338000,
 359000,
 257000,
 252000,
 297000,
 533000,
 371000,
 410000,
 365000,
 423000,
 347000,
 462000,
 335000,
 464000,
 509000,
 431000,
 462000,
 433000,
 545000,
 340000,
 518000,
 324000,
 749000,
 646000,
 495000,
 698000,
 620000,
 580000,
 516000,
 631000,
 721000,
 715000,
 606000,
 693000,
 418000,
 383000,
 543000,
 600000,
 500000,
 561000,
 568000,
 741000,
 423000,
 470000,
 651000,
 654000,
 648000,
 439000,
 536000,
 535000,
 610000,
 610000,
 691000,
 449000,
 524000,
 569000,
 764000,
 350000,
 455000,
 689000,
 434000,
 586000,
 534000,
 554000,
 626000,
 378000,
 576000,
 586000,
 789000,
 419000,
 446000,
 675000,
 386000,
 329000,
 403000,
 470000,
 499000,
 358000,
 350000,
 413000,
 740000,
 515000,
 569000,
 508000,
 588000,
 483000,
 641000,
 465000,
 644000,
 708000,
 599000,
 641000,
 601000,
 758000,
 473000,
 719000,
 450000]

In [6]:
# mean function
def user_mean(prices):
    total =0
    for i in prices:
        total = total + i
    # total sum divided by length
    return total/len(prices)

In [7]:
user_mean(prices)

467700.0

In [8]:
# median function
def user_median(prices):
    # length of prices list
    n = len(prices)
    # sort the prices in ascending order.
    prices.sort()
    # if number of element is even
    # then median is average of n/2 and ((n/2)+1)th element.
    # else element at index n/2
    if n%2==0:
        x = prices[n/2]
        y = prices[(n/2)+1]
        return (x+y)/2
    else:
        return prices[n/2]

In [9]:
# mode function
# its is the most occurring element i.e element with highest count
def user_mode(prices):
    # to keep track of element with max count
    price_counter= 0  # initial count of element
    actual_price = 0 # initial price whose count is maximum
    # find unique element in list
    unique_prices = set(prices)
    
    # for each unique element in prices,compute its number of occurrence
    for i in unique_prices:
        # count the occurrence of each element.
        count = prices.count(i)
        # keep track of element with max count
        if count>price_counter:
            price_counter = count
            actual_price = i
    return actual_price

In [10]:
user_mode(prices)

469000